# Generated by Django 4.2.6 on 2023-10-16 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('danang', 'Đà Nẵng'), ('haiphong', 'Hải Phòng'), ('hue', 'Huế'), ('nhatrang', 'Nha Trang'), ('cantho', 'Cần Thơ'), ('vinh', 'Vinh'), ('quangninh', 'Quảng Ninh'), ('dalat', 'Đà Lạt')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
