# Generated by Django 4.2.6 on 2023-10-19 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('hanoi', 'Hà Nội'), ('hochiminh', 'Hồ Chí Minh'), ('haiphong', 'Hải Phòng'), ('danang', 'Đà Nẵng'), ('hue', 'Huế'), ('nhatrang', 'Nha Trang'), ('cantho', 'Cần Thơ'), ('binhduong', 'Bình Dương'), ('quangninh', 'Quảng Ninh'), ('thanhhoa', 'Thanh Hóa'), ('nghean', 'Nghệ An'), ('hatinh', 'Hà Tĩnh'), ('quangbinh', 'Quảng Bình'), ('quangtri', 'Quảng Trị'), ('thuathienhue', 'Thừa Thiên Huế'), ('quangnam', 'Quảng Nam'), ('quangngai', 'Quảng Ngãi'), ('konturng', 'Kon Tum'), ('daklak', 'Đắk Lắk'), ('gia lai', 'Gia Lai'), ('daknong', 'Đắk Nông'), ('lamdong', 'Lâm Đồng'), ('binhphuoc', 'Bình Phước'), ('binhdinh', 'Bình Định'), ('phuyen', 'Phú Yên'), ('khanhhoa', 'Khánh Hòa'), ('ninhthuan', 'Ninh Thuận'), ('binhthuan', 'Bình Thuận'), ('dongnai', 'Đồng Nai'), ('tayninh', 'Tây Ninh'), ('longan', 'Long An'), ('anlong', 'An Giang'), ('dongsong', 'Đồng Tháp'), ('tiengiang', 'Tiền Giang'), ('bentre', 'Bến Tre'), ('travinh', 'Trà Vinh'), ('vungtau', 'Vũng Tàu'), ('kiengiang', 'Kiên Giang'), ('cambodia', 'Cà Mau'), ('hautinh', 'Hậu Giang'), ('sagiang', 'Sóc Trăng'), ('bacninh', 'Bắc Ninh'), ('bacgiang', 'Bắc Giang'), ('namdinh', 'Nam Định'), ('haiphong', 'Hải Phòng'), ('quangninh', 'Quảng Ninh'), ('ninhbinh', 'Ninh Bình'), ('thanhhoa', 'Thanh Hóa'), ('nghean', 'Nghệ An'), ('hatinh', 'Hà Tĩnh'), ('quangbinh', 'Quảng Bình'), ('quangtri', 'Quảng Trị'), ('thuathienhue', 'Thừa Thiên Huế'), ('quangnam', 'Quảng Nam'), ('quangngai', 'Quảng Ngãi'), ('konturng', 'Kon Tum'), ('daklak', 'Đắk Lắk'), ('gia lai', 'Gia Lai'), ('daknong', 'Đắk Nông'), ('lamdong', 'Lâm Đồng'), ('binhphuoc', 'Bình Phước'), ('binhdinh', 'Bình Định'), ('phuyen', 'Phú Yên'), ('khanhhoa', 'Khánh Hòa'), ('ninhthuan', 'Ninh Thuận'), ('binhthuan', 'Bình Thuận'), ('dongnai', 'Đồng Nai'), ('tayninh', 'Tây Ninh'), ('longan', 'Long An'), ('anlong', 'An Giang'), ('dongsong', 'Đồng Tháp'), ('tiengiang', 'Tiền Giang'), ('bentre', 'Bến Tre'), ('travinh', 'Trà Vinh'), ('vungtau', 'Vũng Tàu'), ('kiengiang', 'Kiên Giang'), ('cambodia', 'Cà Mau'), ('hautinh', 'Hậu Giang'), ('sagiang', 'Sóc Trăng')], max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
