# Generated by Django 4.2.6 on 2023-11-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_orderplaced_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderplaced',
            options={'verbose_name': 'Order Placed', 'verbose_name_plural': 'Order Placed'},
        ),
        migrations.AlterModelTable(
            name='orderplaced',
            table='orderplaced',
        ),
    ]
