# Generated by Django 4.2.6 on 2023-11-04 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderplaced_options_alter_orderplaced_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
