# Generated by Django 4.2.6 on 2023-11-09 07:34

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_created_at_payment_status_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to_brand),
        ),
    ]
