# Generated by Django 4.2.6 on 2023-11-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
