# Generated by Django 4.2.6 on 2023-11-12 07:04

import app.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_alter_product_image_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.uploads.upload_to_news),
        ),
    ]
