# Generated by Django 4.2.6 on 2023-11-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customuser_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
