# Generated by Django 4.2.6 on 2023-11-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='image',
        ),
    ]
