# Generated by Django 4.2.6 on 2023-11-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_avatar_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='is_used',
            field=models.IntegerField(choices=[('Not', '0'), ('Use', '1')], default=0),
        ),
    ]
