# Generated by Django 4.2.6 on 2023-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_avatar_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='is_used',
            field=models.IntegerField(default=0),
        ),
    ]
