# Generated by Django 4.2.6 on 2023-11-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_avatar_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
