# Generated by Django 4.2.6 on 2023-11-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_customer_avatar_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
