# Generated by Django 4.2.6 on 2023-11-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
