# Generated by Django 4.2.6 on 2023-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_cart_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
