# Generated by Django 4.2.6 on 2023-11-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_cart_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='amount',
            new_name='value',
        ),
    ]
