# Generated by Django 4.2.6 on 2023-11-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_amount_orderplaced_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
