# Generated by Django 4.2.6 on 2023-12-13 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0033_remove_news_cat_remove_cart_amount_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerAddress',
        ),
        migrations.AlterModelTable(
            name='customeraddress',
            table='customer_addresses',
        ),
    ]
