# Generated by Django 4.2.6 on 2023-12-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_about_contact_supplier_warehouse_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse_payment',
            name='owner',
        ),
    ]
